spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
             - Path= /clients/**
        - id: r2
          uri: http://localhost:8083/
          predicates:
            - Path= /produits/**
            - Path=/categories/**
